// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzEYyqYwK1UfdscS1apW8jwppbwUaXr1I',
    appId: '1:745871435681:web:7774cece9f9b40e873cde0',
    messagingSenderId: '745871435681',
    projectId: 'uoembu-f3225',
    authDomain: 'uoembu-f3225.firebaseapp.com',
    storageBucket: 'uoembu-f3225.appspot.com',
    measurementId: 'G-F8S4Y1VM3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDnL1b08LX3t5R8VddIw0qkV_AxgMS8QQ',
    appId: '1:745871435681:android:9b3f7f9481fc7f8973cde0',
    messagingSenderId: '745871435681',
    projectId: 'uoembu-f3225',
    storageBucket: 'uoembu-f3225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxaYiporZH1fQ2ThJbOpr-jmXepJpxv60',
    appId: '1:745871435681:ios:2e57113ddd3d294a73cde0',
    messagingSenderId: '745871435681',
    projectId: 'uoembu-f3225',
    storageBucket: 'uoembu-f3225.appspot.com',
    androidClientId: '745871435681-0mikl34vr9qtlrvgkqj4v712s4gncgaf.apps.googleusercontent.com',
    iosClientId: '745871435681-9grv9d6ebhpop9mkngniicht4cm32bnu.apps.googleusercontent.com',
    iosBundleId: 'com.lxmwaniky.slumbernaut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxaYiporZH1fQ2ThJbOpr-jmXepJpxv60',
    appId: '1:745871435681:ios:2e57113ddd3d294a73cde0',
    messagingSenderId: '745871435681',
    projectId: 'uoembu-f3225',
    storageBucket: 'uoembu-f3225.appspot.com',
    androidClientId: '745871435681-0mikl34vr9qtlrvgkqj4v712s4gncgaf.apps.googleusercontent.com',
    iosClientId: '745871435681-9grv9d6ebhpop9mkngniicht4cm32bnu.apps.googleusercontent.com',
    iosBundleId: 'com.lxmwaniky.slumbernaut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzEYyqYwK1UfdscS1apW8jwppbwUaXr1I',
    appId: '1:745871435681:web:4067e40b7d042d8973cde0',
    messagingSenderId: '745871435681',
    projectId: 'uoembu-f3225',
    authDomain: 'uoembu-f3225.firebaseapp.com',
    storageBucket: 'uoembu-f3225.appspot.com',
    measurementId: 'G-05TPNTJJ4K',
  );
}
